# Usa la imagen de Nginx para servir archivos HTML estáticos
FROM nginx:alpine

# Copia el contenido del proyecto en el directorio raíz de Nginx
COPY . /usr/share/nginx/html

# Expone el puerto 80 para acceso desde el exterior
EXPOSE 80