# Usa una imagen oficial de Python como base
FROM python:3.11-slim

# Establece el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copia los archivos desde la máquina host al contenedor (opcional, solo si es necesario)
COPY . .

# Define el comando por defecto para el contenedor
CMD ["bash"]