version: '3.8'

services:
  php-apache:
    build: .
    ports:
      - "8080:80"
    depends_on:
      - mysql-db

  mysql-db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mensajes_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql  # Monta el script de SQL aquí

  adminer:
    image: adminer:latest
    restart: always
    ports:
      - "8081:8080"
    environment:
      ADMINER_DEFAULT_SERVER: mysql-db  # Nombre del servicio de MySQL

volumes:
  mysql_data:
